qerror: drop QERR_SOCKET_CONNECT_IN_PROGRESS
Unused since last commit.

Signed-off-by: Luiz Capitulino <lcapitulino@redhat.com>
Reviewed-by: Markus Armbruster <armbru@redhat.com>