Revert "target-alpha: Add vector implementation for CMPBGE"
This reverts commit 32ad48abd74a997220b841e4e913edeb267aa362.

Unfortunately the SSE2 code here fails to compile on some versions
of gcc:
 target-alpha/int_helper.c:77:24: error: invalid operands to binary >=
 (have '__vector(16) unsigned char' and '__vector(16) unsigned char')

Signed-off-by: Peter Maydell <peter.maydell@linaro.org>